### ISSUE TITLE
Undefined reference to 'i2c_smbus_write_byte_data'

### ISSUE THREAD

**Issue by TNemes-3141** [simondlevy/CrossPlatformI2C#2]
Hello,
When running `make`, I came across several errors caused by referencing missing functions, specifically:
```
g++ -std=c++11 -Wall -I/home/tamas/CrossPlatformDataBus/extras/i2c/i2cdev/src -I/home/tamas/CrossPlatformDataBus/src -c /home/tamas/CrossPlatformDataBus/extras/i2c/i2cdev/src/I2CDevI2C.cpp
g++ -std=c++11 -o MPU_WhoAmI MPU_WhoAmI.o I2CDevI2C.o main.o 
I2CDevI2C.o: In function `cpi2c_writeRegister(unsigned char, unsigned char, unsigned char)':
I2CDevI2C.cpp:(.text+0x148): undefined reference to `i2c_smbus_write_byte_data'
I2CDevI2C.o: In function `cpi2c_readRegisters(unsigned char, unsigned char, unsigned char, unsigned char*)':
I2CDevI2C.cpp:(.text+0x180): undefined reference to `i2c_smbus_write_byte'
I2CDevI2C.cpp:(.text+0x19c): undefined reference to `i2c_smbus_read_byte'
I2CDevI2C.o: In function `cpi2c_writeRegister_16_8(unsigned char, unsigned short, unsigned char)':
I2CDevI2C.cpp:(.text+0x1f8): undefined reference to `i2c_smbus_write_byte_data'
I2CDevI2C.o: In function `cpi2c_readRegister_8_16(unsigned char, unsigned char)':
I2CDevI2C.cpp:(.text+0x228): undefined reference to `i2c_smbus_write_byte'
I2CDevI2C.cpp:(.text+0x234): undefined reference to `i2c_smbus_read_word_data'
collect2: error: ld returned 1 exit status
Makefile:29: recipe for target 'MPU_WhoAmI' failed
make: *** [MPU_WhoAmI] Error 1
```
I did some reading, check the included headers and discovered that in the newer versions of `i2c-dev` and `i2c-tools` (newest is 4.0), used functions are deprecated and no longer defined. I know the library is old as well, but can you give me some kind of workaround to fix this or is there (or will there be) an updated version of the CrossPlatformDataBus library?
_Thanks for your answer in advance!_

**Comment by simondlevy** [comment]
Thanks, I'm working on it.  Should have a fix within next two weeks.

**Comment by TNemes-3141** [comment]
Hello,
That's great to hear! I want to use CrossPlatformDataBus with your MPU library to control my MPU 9250 Sensor, and this seemed the easiest and cleanest way to me. I just hope the two continue to be compatible after the update. Thanks!

**Comment by simondlevy** [comment]
Okay, I was able to replicate the error and appear to have fixed it: I can now build extras/i2c/i2cdev/examples/MPU_WhoAmI.  But I have only done this on my Ubuntu desktop machine, not on a Jetson or other device supporting actual I^2C.  So you should pull the updated repo, try it out yourself on your device, and let me know what you get.

**Comment by TNemes-3141** [comment]
Hey,
many thanks for your work so far, it seems to be working now! I was able to successfully build it and for my MPU9250 it returns: `I am 0x71`
I then tried to build your MPU library to see if it's working, but I came across the same type of issue in the making process there:
```
g++ -std=c++11 -o MasterTest MasterTest.o MPU.o MPU9250.o MPU9250_Master.o MPU9250_Master_I2C.o I2CDevI2C.o main.o timing.o errmsg.o
I2CDevI2C.o: In function `cpi2c_writeRegister(unsigned char, unsigned char, unsigned char)':
I2CDevI2C.cpp:(.text+0x148): undefined reference to `i2c_smbus_write_byte_data'
I2CDevI2C.o: In function `cpi2c_readRegisters(unsigned char, unsigned char, unsigned char, unsigned char*)':
I2CDevI2C.cpp:(.text+0x180): undefined reference to `i2c_smbus_write_byte'
I2CDevI2C.cpp:(.text+0x19c): undefined reference to `i2c_smbus_read_byte'
I2CDevI2C.o: In function `cpi2c_writeRegister_16_8(unsigned char, unsigned short, unsigned char)':
I2CDevI2C.cpp:(.text+0x1f8): undefined reference to `i2c_smbus_write_byte_data'
I2CDevI2C.o: In function `cpi2c_readRegister_8_16(unsigned char, unsigned char)':
I2CDevI2C.cpp:(.text+0x228): undefined reference to `i2c_smbus_write_byte'
I2CDevI2C.cpp:(.text+0x234): undefined reference to `i2c_smbus_read_word_data'
collect2: error: ld returned 1 exit status
g++ -std=c++11 -o PassthruTest PassthruTest.o MPU.o MPU9250.o MPU9250_Passthru.o I2CDevI2C.o main.o timing.o errmsg.o
Makefile:33: recipe for target 'MasterTest' failed
make: *** [MasterTest] Error 1
make: *** Waiting for unfinished jobs....
I2CDevI2C.o: In function `cpi2c_writeRegister(unsigned char, unsigned char, unsigned char)':
I2CDevI2C.cpp:(.text+0x148): undefined reference to `i2c_smbus_write_byte_data'
I2CDevI2C.o: In function `cpi2c_readRegisters(unsigned char, unsigned char, unsigned char, unsigned char*)':
I2CDevI2C.cpp:(.text+0x180): undefined reference to `i2c_smbus_write_byte'
I2CDevI2C.cpp:(.text+0x19c): undefined reference to `i2c_smbus_read_byte'
I2CDevI2C.o: In function `cpi2c_writeRegister_16_8(unsigned char, unsigned short, unsigned char)':
I2CDevI2C.cpp:(.text+0x1f8): undefined reference to `i2c_smbus_write_byte_data'
I2CDevI2C.o: In function `cpi2c_readRegister_8_16(unsigned char, unsigned char)':
I2CDevI2C.cpp:(.text+0x228): undefined reference to `i2c_smbus_write_byte'
I2CDevI2C.cpp:(.text+0x234): undefined reference to `i2c_smbus_read_word_data'
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'PassthruTest' failed
make: *** [PassthruTest] Error 1
```
Is there a way you could fix that one  in the same way, too? It would be a huge help!

**Comment by simondlevy** [comment]
Thanks for pointing this out.  I've modified the Makefile to eliminate the error.  Pull the MPU repo again, give it another try, and let me know what you get.

**Comment by TNemes-3141** [comment]
Hey,
your code is working for me! It measures the values and displays them accordingly, so thanks again for the fix!
The one thing I don't understand is what gyro temperature is saying. Does the chip have a built-in  sensor just to measure the temperature of the gyroscope? The value it gives does not match the environmental temperature.

**Comment by simondlevy** [comment]
Great, I'm glad it works, and I appreciate your pointing out the issue.

As for the gyro temperature: I've never had a use for it, so I pretty much ignore the values that it delivers, which ,as you've seen, do not always make sense.  If you find a way to improve it, I'll be happy to add that code to the MPU repository.  Meanwhile I will close the issue here (i2c_smbus_*).
